# Generated by Django 4.2 on 2023-04-10 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='TaskIT',
        ),
    ]
