# Generated by Django 4.2 on 2023-04-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_category_taskit_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskit',
            options={'ordering': [], 'verbose_name': 'Списки заказов от заказчиков', 'verbose_name_plural': 'Списки заказов от заказчиков'},
        ),
        migrations.AddField(
            model_name='taskit',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='taskit',
            name='time_update',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
