# Generated by Django 4.1 on 2023-04-12 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0007_chooserole_alter_category_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChooseRole',
        ),
        migrations.AddField(
            model_name='taskit',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
